git config --global user.email "${GIT_USER_EMAIL}"
git config --global user.name "${GIT_USER_NAME}"

echo ""
echo "- Set git config to: NAME: '${GIT_USER_NAME}' eMail: '${GIT_USER_EMAIL}'"
echo ""
echo "-----------------------------------------"
echo "Welcome to AOSP Marshmallow 6.0 Builder.."
echo "-----------------------------------------"
echo ""
echo "- User: $(whoami) [$(id -u $USER)] | Group: $(id -g -n) [$(id -g)]"
echo "- HOME: ${HOME}"
echo "- WORKDIR: ${WORKDIR}"
echo ""
